# Generated by Django 4.2.7 on 2025-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills', null=True),
        ),
    ]
