# Generated by Django 4.2.7 on 2025-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_github_user_linkedin_user_twitter_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
