# Generated by Django 4.2.7 on 2025-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, help_text='Education history, degrees, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, help_text='Work experience, jobs, etc.', null=True),
        ),
    ]
