# Generated by Django 5.2.3 on 2025-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('student', 'Student'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
