from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from .views import (
    UserRegisterView,
    MyTokenObtainPairView,
    ProfileView,
    PublicProfileView,
    AlumniSearchView,
    ConnectionRequestViewSet,
    MessageViewSet,
    PostViewSet,
    GlobalSearch,
    public_alumni,
    public_profile,
    user_posts,
    public_stats,
    public_feed,
    password_reset_request,
    password_reset_confirm,
    like_post,
    add_post_comment,
    list_post_comments,
    delete_post_comment,
    list_notifications,
    mark_notification_read,
    mark_all_notifications_read,
    endorse_skill,
    list_endorsements,
    add_recommendation,
    list_recommendations,
    report_content,
    list_reports,
    resolve_report,
    my_connections,
    comment_like,
    unread_message_count,
    mark_messages_read,
    recommendations,
    admin_dashboard,
)

router = DefaultRouter()
router.register(r'connections', ConnectionRequestViewSet, basename='connectionrequest')
router.register(r'messages', MessageViewSet, basename='message')
router.register(r'posts', PostViewSet, basename='post')

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('profile/', ProfileView.as_view(), name='user_profile'),
    path('profile/<int:pk>/', PublicProfileView.as_view(), name='public_profile'),
    path('alumni/search/', AlumniSearchView.as_view(), name='alumni_search'),
    path('search/alumni/', AlumniSearchView.as_view(), name='alumni_search_alt'),
    path('search/', GlobalSearch.as_view(), name='global_search'),
    path('public-alumni/', public_alumni, name='public-alumni'),
    path('public-profile/<int:id>/', public_profile, name='public-profile'),
    path('posts/user/<int:id>/', user_posts, name='user-posts'),
    path('public-stats/', public_stats, name='public-stats'),
    path('feed/', public_feed, name='public-feed'),
    path('recommendations/', recommendations, name='recommendations'),
    path('password-reset/', password_reset_request, name='password_reset_request'),
    path('password-reset/confirm/', password_reset_confirm, name='password_reset_confirm'),
    path('posts/<int:post_id>/like/', like_post, name='like_post'),
    path('posts/<int:post_id>/comments/', add_post_comment, name='add_post_comment'),
    path('posts/<int:post_id>/comments/', list_post_comments, name='list_post_comments'),
    path('comments/<int:comment_id>/', delete_post_comment, name='delete_post_comment'),
    path('notifications/', list_notifications, name='list_notifications'),
    path('notifications/<int:pk>/read/', mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', mark_all_notifications_read, name='mark_all_notifications_read'),
    path('users/<int:user_id>/endorse/', endorse_skill, name='endorse_skill'),
    path('users/<int:user_id>/endorsements/', list_endorsements, name='list_endorsements'),
    path('users/<int:user_id>/recommend/', add_recommendation, name='add_recommendation'),
    path('users/<int:user_id>/recommendations/', list_recommendations, name='list_recommendations'),
    path('reports/', report_content, name='report_content'),
    path('reports/', list_reports, name='list_reports'),
    path('reports/<int:report_id>/resolve/', resolve_report, name='resolve_report'),
    path('my-connections/', my_connections, name='my_connections'),
    path('comments/<int:comment_id>/like/', comment_like, name='comment-like'),
    path('messages/unread-count/', unread_message_count, name='unread-message-count'),
    path('messages/with/<int:user_id>/mark-read/', mark_messages_read, name='mark-messages-read'),
    path('admin/dashboard/', admin_dashboard, name='admin-dashboard'),
    path('', include(router.urls)),
] 